### ISSUE TITLE
How can I get the data permission？

### ISSUE THREAD

**Issue by xugangtongji** [moveithackathon-canhack/traffic-gesture-recognition#1]
Hello, I am a student. I am very interested in human behavior detection. So can I use your data to train my own model?

**Comment by awesomebytes** [comment]
In short: yeah, sure.

In longer: the data may be pending to be uploaded. But it should be open
data once it is (that was the nature of the event where the data was
gathered).

**Comment by xugangtongji** [comment]
@awesomebytes  Nice, Thank you！This project is awesome, I like it.

**Comment by yjmade** [comment]
Sorry, I have now made the download link public, try again

**Comment by xiaoying-123623** [comment]
Hello, now the dataset can't be downloaded, can you share it again, excuse me
